/**
 * Doctor / pharmacy report.
 *
 * Builds a printable HTML summary of medications, adherence, and recent events and
 * renders it to a PDF with expo-print, then hands it to the share sheet via
 * expo-sharing. Both work in Expo Go (SDK 54).
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { CareEvent, DoseLog, LovedOne, Medication } from '../types';
import { adherenceStats, medTimes } from './adherence';
import { DISCLAIMER } from './interactions';

const REPORT_DAYS = 30;

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmtDate(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtDateTime(ts: number): string {
  return new Date(ts).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

export function buildReportHtml(
  lovedOne: LovedOne,
  meds: Medication[],
  doseLogs: DoseLog[],
  events: CareEvent[],
  now: number,
): string {
  const stats = adherenceStats(meds, doseLogs, now, REPORT_DAYS);
  const since = now - REPORT_DAYS * 24 * 60 * 60 * 1000;
  const periodEvents = events.filter((e) => e.at >= since && e.severity !== 'info').slice(0, 40);

  const medRows = meds
    .map((m) => {
      const a = stats.byMed.find((x) => x.med.id === m.id);
      const times = medTimes(m).join(', ') || 'as needed';
      return `<tr>
        <td><strong>${esc(m.name)}</strong>${m.critical ? ' <span class="tag">critical</span>' : ''}</td>
        <td>${esc(m.dosage)}</td>
        <td>${esc(times)}</td>
        <td>${a ? `${a.adherencePct}% (${a.taken}/${a.taken + a.missed})` : '—'}</td>
      </tr>`;
    })
    .join('');

  const eventRows = periodEvents.length
    ? periodEvents
        .map(
          (e) =>
            `<tr><td>${esc(fmtDateTime(e.at))}</td><td>${esc(e.severity)}</td><td>${esc(e.title)}${
              e.detail ? ` — ${esc(e.detail)}` : ''
            }</td></tr>`,
        )
        .join('')
    : `<tr><td colspan="3">No notable events in this period.</td></tr>`;

  const allergies = lovedOne.allergies?.length ? lovedOne.allergies.map(esc).join(', ') : 'None recorded';
  const conditions = lovedOne.conditions?.length ? lovedOne.conditions.map(esc).join(', ') : 'None recorded';

  return `<!doctype html><html><head><meta charset="utf-8"><style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #12171E; padding: 28px; }
    h1 { font-size: 24px; margin: 0 0 2px; }
    .sub { color: #505A66; font-size: 13px; margin-bottom: 18px; }
    h2 { font-size: 15px; border-bottom: 2px solid #E3E8ED; padding-bottom: 4px; margin-top: 24px; }
    .cards { display: flex; gap: 12px; margin: 12px 0; }
    .card { flex: 1; background: #F4F6F8; border-radius: 10px; padding: 12px; }
    .card .n { font-size: 26px; font-weight: 800; }
    .card .l { font-size: 12px; color: #505A66; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
    th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #EAEEF2; vertical-align: top; }
    th { color: #505A66; font-weight: 600; }
    .tag { background: #FADCDA; color: #B23434; font-size: 10px; padding: 1px 6px; border-radius: 6px; }
    .disclaimer { margin-top: 24px; font-size: 11px; color: #6B7480; line-height: 1.5; }
  </style></head><body>
    <h1>${esc(lovedOne.name)} — Care Summary</h1>
    <div class="sub">${esc(lovedOne.relationship)} · ${fmtDate(since)} – ${fmtDate(now)} · generated by Ambient Care</div>

    <div class="cards">
      <div class="card"><div class="n">${stats.adherencePct}%</div><div class="l">Adherence (${REPORT_DAYS}d)</div></div>
      <div class="card"><div class="n">${stats.missedCount}</div><div class="l">Doses missed</div></div>
      <div class="card"><div class="n">${stats.currentStreak}</div><div class="l">Day streak</div></div>
    </div>

    <h2>Medical profile</h2>
    <table>
      <tr><th>Blood type</th><td>${esc(lovedOne.bloodType || '—')}</td></tr>
      <tr><th>Allergies</th><td>${allergies}</td></tr>
      <tr><th>Conditions</th><td>${conditions}</td></tr>
      <tr><th>Doctor</th><td>${esc(lovedOne.doctor || '—')}</td></tr>
      <tr><th>Pharmacy</th><td>${esc(lovedOne.pharmacy || '—')}</td></tr>
    </table>

    <h2>Medications</h2>
    <table>
      <tr><th>Medication</th><th>Dosage</th><th>Times</th><th>Adherence</th></tr>
      ${medRows || '<tr><td colspan="4">No medications recorded.</td></tr>'}
    </table>

    <h2>Notable events (${REPORT_DAYS} days)</h2>
    <table>
      <tr><th>When</th><th>Level</th><th>Event</th></tr>
      ${eventRows}
    </table>

    <div class="disclaimer">${esc(DISCLAIMER)}</div>
  </body></html>`;
}

export async function exportReport(
  lovedOne: LovedOne,
  meds: Medication[],
  doseLogs: DoseLog[],
  events: CareEvent[],
  now: number,
): Promise<void> {
  const html = buildReportHtml(lovedOne, meds, doseLogs, events, now);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf' });
  }
}
